apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: ecommerce
  labels:
    app: inventory-service
    part-of: ecommerce
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
