apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - order-service/deployment.yaml
  - order-service/service.yaml
  - inventory-service/deployment.yaml
  - inventory-service/service.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - postgres/pvc.yaml
  - postgres/configmap.yaml
  - secrets/db-secret.yaml

commonLabels:
  part-of: ecommerce
